exports.Program = 'Program'
exports.ExpressionStatement = 'ExpressionStatement' // 表达式语句
exports.JSXElement = 'JSXElement' // JSX元素
exports.JSXOpeningElement = 'JSXOpeningElement' // 开始元素
exports.JSXIdentifier = 'JSXIdentifier' // 标识符
exports.JSXAttribute = 'JSXAttribute' // 属性
exports.Literal = 'Literal' // 字符串字面量
exports.JSXClosingElement = 'JSXClosingElement' // 结束元素
exports.JSXText = 'JSXText' // 文本
exports.NullLiteral = 'NullLiteral' // 空的Null节点
exports.StringLiteral = 'StringLiteral' // 字符串字面量
exports.Identifier = 'Identifier'  // 标识符，就是变量的意思
exports.ObjectExpression = 'ObjectExpression' // 对象属性
exports.Property = 'Property' // 属性
exports.CallExpression = 'CallExpression'
exports.MemberExpression = 'MemberExpression'